Auction_authenticate/config/routes.rb
Rails.application.routes.draw do
  root to: 'users#home'

  get '/signup' => 'users#new'
  get '/profile' => 'users#show'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :users, only: [:new, :index, :create, :destroy] do
    resources :products, only: [:index, :show, :new, :create, :destroy] do
      resources :bids, only: [:create]
      resources :reviews, only: [:new, :create]
    end
  end
end

Auction_authenticate/app/models/bid.rb
class Bid < ActiveRecord::Base
  validates :amount, presence: true
  
  belongs_to :product
end

Auction_authenticate/app/models/product.rb
class Product < ActiveRecord::Base
  validates :title, :description, :deadline, presence: true

  belongs_to :user
  has_many :bids
  has_many :reviews

  def active_bid?
    self.deadline > Date.current.end_of_day
  end

  def get_winner_user
    winner_bid = get_winner_bid
    User.find_by(id: winner_bid.user_id)
  end

  def get_winner_bid
    self.bids.order(amount: :desc).first
  end
end

Auction_authenticate/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

Auction_authenticate/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

  validates :email, presence: true
  validates :email, uniqueness: true

  has_many :products
end

Auction_authenticate/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
  	@current_user ||= User.find_by_id(session[:user_id])
  end

  def authorize_user
  	unless current_user
  		flash[:message] = "Signup please!"
  		redirect_to :login
  	end
  end

  def render_404(params)
    Rails.logger.warn("Tried to access #{params} which did not exist.")
    render 'layouts/404'
  end
end

Auction_authenticate/app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def create
    email = params[:bid][:email]
    amount = params[:bid][:amount]

    user = User.find_by(email: email)
    product = Product.find_by(id: params[:product_id])
    bid = product.bids.new(user_id: user.id, amount: amount, product_id: product.id)

    if(bid.save)
      flash[:notice] = "Your bid was correctly send! Good luck!"
    else
      flash[:alert] = "Something went wrong"
    end

    redirect_to(user_product_path(product.user_id, product))
  end
end

Auction_authenticate/app/controllers/products_controller.rb
require 'pry'

class ProductsController < ApplicationController
  def index
    @user = User.find_by(id: params[:user_id])
    @products = @user.products
  end

  def show
    @user = User.find_by(id: params[:user_id])
    @product = @user.products.find_by(id: params[:id])
    @reviews = @product.reviews

    if(@product.active_bid?)
      @bids = @product.bids
    else
      @winner_user = @product.get_winner_user
      @winner_bid = @product.get_winner_bid
    end
  end

  def new
    @user = User.find_by(id: params[:user_id])
    @product = @user.products.new
  end

  def create
    @user = User.find_by(id: params[:user_id])
    @product = @user.products.new(entry_params)

    if(@product.save)
      flash[:notice] = "Product created successfully"
      redirect_to(user_products_path(@user))
    else
      flash[:alert] = "Something went wrong"
      render('new')
    end
  end

  def destroy

  end

  private

  def entry_params
    params.require(:product).permit(:title, :description, :deadline)
  end
end

Auction_authenticate/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :authorize_user, only: [:create]

	def create
		description = params[:review][:description]

		user = User.find_by(id: params[:user_id])
		product = Product.find_by(id: params[:product_id])

		@review = product.reviews.new(user_id: user.id, description: description, product_id: product.id)

		if @review.save
			flash[:notice] = 'Review saved'
		else
			flash[:alert] = 'Sorry, something went wrong'
		end

		redirect_to(user_product_path(product.user_id, product))	
	end
end

Auction_authenticate/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(name: params[:name])

		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to '/profile'
		else
			redirect_to '/login'
		end
	end

	def destroy
		session.clear
		redirect_to '/'
	end

end

Auction_authenticate/app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    @products = Product.all
  end
end

Auction_authenticate/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home
    @name = current_user ? current_user.name : "Ironhacker"
  end

  def index
    @users = User.all.order("name ASC")
  end

  def show
    @products = current_user.products
    @reviews = @products.reviews
  end

  def new
    @user = User.new
  end

  def destroy

  end

  def create
    @user = User.new(entry_params)

    if @user.save
      flash[:notice] = "User created successfully!"
      redirect_to '/'
    else
      flash[:alert] = "Something went wrong"
      render :new
    end
  end

  private

  def entry_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

Auction_authenticate/app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message
    get_message(:notice) || get_message(:alert)
  end

  def format_date(date)
    date.strftime("%d-%m-%Y")
  end

  def format_price(price)
    sprintf('%.2f', price)
  end

  private

  def get_message(type)
    if flash[type]
      content_tag :div, class: "message #{type.to_s}" do
        flash[type]
      end
    end
  end
end

Auction_authenticate/app/helpers/bids_helper.rb
module BidsHelper
  def get_user_name user_id
    user = User.find_by(id: user_id)
    user.name
  end
end

Auction_authenticate/app/helpers/products_helper.rb
module ProductsHelper
end

Auction_authenticate/app/helpers/reviews_helper.rb
module ReviewsHelper
end

Auction_authenticate/app/helpers/sessions_helper.rb
module SessionsHelper
end

Auction_authenticate/app/helpers/site_helper.rb
module SiteHelper
end

Auction_authenticate/app/helpers/user_helper.rb
module UserHelper
end

Auction_authenticate/app/views/layouts/404.html.erb
404 - Error Page

Auction_authenticate/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuctionSite</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>AUCTION TIME BABIEES!</h1>

	<% flash.each do |key, msg| %>
		<%= content_tag :div, msg, id: key, style: "color:red;" %>
	<% end %>

	<% if current_user %>
		<h1>Hi <%= current_user.name %>!</h1>
		<%= link_to "Logout", "/logout", method: :delete%><br>
	<% else %>
		<%= link_to "Login", "/login" %><br>
	<% end %>

<%= yield %>

</body>
</html>

Auction_authenticate/app/views/products/index.html.erb
<h2><%= @user.name %> products</h2>

<% if(@products.any?) %>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to(product.title, user_product_path(@user, product)) %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to("Add new product", new_user_product_path(@user)) %>

Auction_authenticate/app/views/products/new.html.erb
<h2>Add new product</h2>

<%= flash_message %>

<% if(@product.errors.any?) %>
  <ul>
    <% @product.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [@user, @product] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.label :deadline %>
  <%= f.date_field :deadline %>
  <br>
  <%= f.submit "Save" %>
<% end %>

Auction_authenticate/app/views/products/show.html.erb
<h2><%= @product.title %></h2>
<strong>Seller: <%= @user.name %></strong>
<em>Deadline date: <%= format_date(@product.deadline) %></em>


<% if(@product.active_bid?) %>
  <h3>I want the product!</h3>

  <%= flash_message %>

  <form action="/users/<%= @user.id %>/products/<%= @product.id %>/bids" method="post">
    <input name="authenticity_token" type="hidden" value="J7CBxfHalt49OSHp27hblqK20c9PgwJ108nDHX/8Cts=" />
    <label for="email">E-Mail address</label>
    <br>
    <input type="email" name="[bid]email" id="email" required>
    <br>
    <label for="bid">Bid</label>
    <br>
    <input type="numeric" name="[bid]amount" id="bid" required>
    <br>
    <button type="submit">Send my bid</button>
  </form>

  <% if(@bids.any?) %>
    <h3>List of bids</h3>
    <ul>
      <% @bids.each do |bid| %>
        <li><%= get_user_name(bid.user_id) %> <%= format_price(bid.amount) %> €</li>
      <% end %>
    </ul>
  <% end %>

<% else %>
  <h3>The auction has finished</h3>
  <p>The winner was: <%= @winner_user.name %> paying <%= format_price(@winner_bid.amount) %> €</p>
<% end %>


<% if current_user %>
  <form action="/users/<%= @user.id %>/products/<%= @product.id %>/reviews" method="post">
    <input name="authenticity_token" type="hidden" value="J7CBxfHalt49OSHp27hblqK20c9PgwJ108nDHX/8Cts=" />
    <p>Add your review for this product</p>
    <input type="text" name="[review]description" id='review' required>
    <button type="submit">Add review</button>
  </form>
<% end %>


<% if(@reviews.any?) %>
  <h3>Reviews</h3>
  <ul>
    <% @reviews.each do |rvw| %>
      <li><%= rvw.description %></li>
    <% end %>
  </ul>
<% end %>

Auction_authenticate/app/views/site/home.html.erb
<% if(@products.any?) %>
  <% @products.each do |product| %>
    <div style="float: left; margin: 0 50px 70px 0">
      <h2><%= link_to(product.title, user_product_path(product.user_id, product)) %></h2>
      <p><%= product.description %></p>
      <p><strong>Dead line: <%= format_date(product.deadline) %></strong></p>
      <em>Owner: <%= product.user.name %></em>
    </div>
  <% end %>
<% end %>

Auction_authenticate/app/views/users/home.html.erb
<% if current_user %>
	<%= link_to "My profile", "/profile" %><br>
	<%= link_to "All profiles", "/users" %>
<% else %>

<h1><%= @name %>, login if you want to start bidding</h1>

	<%= link_to "Login", "/login" %><br>
  <%= link_to "Sign up", "/signup" %><br>
  <%= link_to "All profiles", "/users" %>

<%end%>

Auction_authenticate/app/views/users/index.html.erb
<h2>User's list</h2>

<% if(@users.any?) %>
  <ul>
    <% @users.each do |user| %>
      <li><%= user.name %> | <%= link_to("Products", user_products_path(user)) %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to("New user", new_user_path) %>

Auction_authenticate/app/views/users/new.html.erb
<h2>Create a new user</h2>

<%= flash_message %>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [@user] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit "Save" %>
<% end %>

Auction_authenticate/app/views/users/show.html.erb
<p>Welcome back!</p>


<% if(@products.any?) %>
  <h3>Products</h3>
  <ul>
    <% @products.each do |p| %>
      <li><%= p.title %></li>
      <li><% p.reviews do |r| %></li>
      	<ul>
      		<li><%= r.description %></li>
      	</ul>
      <% end %>
    <% end %>
  </ul>
<% else %>
	<p>No products available</p>
<% end %>